---
- name: install nginx on node2 group servers
  hosts: node2
  become: yes
  tasks:
  - name: install nginx 
    apt:
      name: nginx
      state: present
- name: stop apache2 service on node1
  hosts: node1
  become: yes
  tasks:
  - name: stop apache2 service
    service: 
      name: apache2
      state: stopped

